notifications:
  email: false
  slack:
    rooms:
      secure: nzKJCv7Aekdllh8hqBJcwEzXVt7Qo1u0rH8/oJRq8MPGIlPNIebikC20KMy2SISo5ygI8ULebMzEePPuMin4NFs1YyLQ6aNOyITaY/EQGq9oTfDshOX5ZNACw2RLsjx6DHM9XJyITYbGJ2KLyhUY6UyVGoDKKV9ybANtObNv4qao0P4SYOWK9z/O5WWvXEuGI9ks3LIuO9b/y1Kd8iK+4Zrff9orIWXWrHWyvBhEMfGqesX81JZr7XIXTIU3Y5CPU2574rM6mU4imywmOOa5SywUEXZzI3NfSkyFbqelMwPJA8m7xSTiyuL4UbeFGpqPhNQjexdcNDWcHp+JTNbXhedq2yRZXA8mYhrFPgmLChosRxameFKKxviy5ut171KwGiO8h35FpKOYRxBtQKdpE1TVOt5hpsOFpEPcDPjnCRpBmS7zER4LVgkFwRAy389Vb3keZLpLee6UZOUexjqjr9evof17Q0AT2MfKThPvjOYywWjhF7LBqfceDwlvucEtZ/pcOeMODYcJUka57/87RY2ufY6JJRHQ7836++HWtQbmeJXNXfyB3j+b5se29D3Bw8OfqNMGdMq0Iex3Fmlj2XJ7jGpuHcaLQ2SEaJilPf4GdYzPb4QF8hwnVEBQwPiPJymrLVWKXG18SB9jLTht1PCe/xZ3/zgtl/ExskU7Gfs=
    on_success: always
    on_failure: always

stages:
- name: DOC
- name: TEST_AWS
- name: TEST_OVH
- name: TEST_SCW

env:
  - PROVIDER=aws
  - PROVIDER=ovh
  - PROVIDER=scw

jobs:
  include:

  - stage: DOC
    if: commit_message !~ /\[skip doc\]/
    language: node_js
    node_js:
    - '8'
    script:
    - bash .travis.doc.sh
    deploy:
      provider: pages
      local-dir: docs/.vuepress/dist
      skip-cleanup: true
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      on:
        branch: master

  - stage: TEST
    if: commit_message !~ /\[skip test\]/
    language: node_js
    node_js:
    - '8'
    script:
    - bash .travis.test.sh test-$PROVIDER
    env: PROVIDER=aws

 