notifications:
  email: false
  slack:
    rooms:
      secure: nzKJCv7Aekdllh8hqBJcwEzXVt7Qo1u0rH8/oJRq8MPGIlPNIebikC20KMy2SISo5ygI8ULebMzEePPuMin4NFs1YyLQ6aNOyITaY/EQGq9oTfDshOX5ZNACw2RLsjx6DHM9XJyITYbGJ2KLyhUY6UyVGoDKKV9ybANtObNv4qao0P4SYOWK9z/O5WWvXEuGI9ks3LIuO9b/y1Kd8iK+4Zrff9orIWXWrHWyvBhEMfGqesX81JZr7XIXTIU3Y5CPU2574rM6mU4imywmOOa5SywUEXZzI3NfSkyFbqelMwPJA8m7xSTiyuL4UbeFGpqPhNQjexdcNDWcHp+JTNbXhedq2yRZXA8mYhrFPgmLChosRxameFKKxviy5ut171KwGiO8h35FpKOYRxBtQKdpE1TVOt5hpsOFpEPcDPjnCRpBmS7zER4LVgkFwRAy389Vb3keZLpLee6UZOUexjqjr9evof17Q0AT2MfKThPvjOYywWjhF7LBqfceDwlvucEtZ/pcOeMODYcJUka57/87RY2ufY6JJRHQ7836++HWtQbmeJXNXfyB3j+b5se29D3Bw8OfqNMGdMq0Iex3Fmlj2XJ7jGpuHcaLQ2SEaJilPf4GdYzPb4QF8hwnVEBQwPiPJymrLVWKXG18SB9jLTht1PCe/xZ3/zgtl/ExskU7Gfs=
    on_success: always
    on_failure: always

stages:
- name: PUBLISH

jobs:
  include:

  - stage: PUBLISH
    language: node_js
    node_js:
    - '8'
    script:
    - yarn install
    - npm run docs:build
    deploy:
      provider: pages
      local-dir: docs/.vuepress/dist
      skip-cleanup: true
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      on:
        branch: master

  - stage: TEST
    if: commit_message =~ (\[tests\])
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    before_script:
    - curl -fSL "https://releases.hashicorp.com/terraform/0.11.4/terraform_0.11.4_linux_amd64.zip" -o terraform.zip
    - sudo unzip terraform.zip -d /opt/terraform
    - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
    - rm -f terraform.zip
    - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
    - git clone https://github.com/kalisio/kaabah-workspaces ../workspaces/master
 
    script:
    - terraform init -backend-config="backend.config"
    - terraform workspace select test-aws
    - terraform apply -var-file="tests/test-aws.tfvars"
    - terraform destroy -var-file="tests/test-aws.tfvars"
    - terraform workspace select test-ovh
    - terraform apply -var-file="tests/test-ovh.tfvars"
    - terraform destroy -var-file="tests/test-ovh.tfvars"      
    - terraform workspace select test-scw
    - terraform apply -var-file="tests/test-scw.tfvars"
    - terraform destroy -var-file="tests/test-scw.tfvars" 
