language: node_js
node_js:
  - 8
services:
- docker
notifications:
  email: false
  slack:
    rooms:
      secure: NEcm37UG/JKr1xZkVchn/4/YokJd9VlCam13EDqaTPzyVGi2zJcJfXF6zAMLrUvdYpq7PIeFs/QRQufpcwuEoJgfboYnV2G1MPiL+YRlJojvx1PLuVcmSNdMJDrPBJ6UOYHAiwaLYgQljtDVoQz3xSwi2YAcBwyuwqfQBNNxoxQuWV7O31O0PMfp5PyBrxDCy1dwrDpO1bnNA8ohpoUxv9+1wAfTI88DmCOZ73vUJRHGohya2CaELDOA7L/i35tG5T1k7EAW6tb6HTFlyTVLeDiEr3mGNs79//JmPPt7LTOnZA9s9IDbCOQprFMPmLpWglXr2CXTb+wPDUTRNmr81j57Z+edzzdkFa8/zM6vhc9Ty7hsaHnJhD5hvMay2H4fEKtPdEP1nizuNqW5qvf1dq7c8Ct1cnr9FSWbP2TQ5By53Pa/Wi0w1pSpPpuK14/EgHsUH7mxjqIca7YBL996ZBp0u1Ii/Sx8oP9o5NnIsIJEYPw6Wjm7OsYY7vX136JKeMYNoeg15o1nt1zFMzYrU8GN/5PyTjFizOcFUXxyER17RxTu0ZV7xltZH2xRgTB6f0h99+T0B0kfsJB6zer1OJGepGHTFQVTMzH85c3Srhk/U0l5ja3fWet2AGzlRwKFja1hGNiwRtfeU5sILJh0KSOG/0O4faXVvIWYdODIWH4=
    on_success: always
    on_failure: always  

before_install:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in ssh.pem.enc -out ssh.pem -d

script:
  - docker build -t kalisio/whoami .

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
  - docker push kalisio/whoami

before_deploy:
  # install terraform
  - curl -fSL "https://releases.hashicorp.com/terraform/0.11.4/terraform_0.11.4_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
