language: node_js
node_js:
  - 8
services:
- docker

before_install:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in ssh.pem.enc -out ssh.pem -d

script:
  - ls
  - docker build -t kalisio/whoami .

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
  - docker push kalisio/whoami

before_deploy:
  # install terraform
  - curl -fSL "https://releases.hashicorp.com/terraform/0.11.4/terraform_0.11.4_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
