version: '3'

services:
  traefik:
    image: traefik
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme:/acme
    container_name: traefik
    labels:
      - "traefik.backend=traefik"
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:traefik.kalisio.xyz"

  portainer:
    image: portainer/portainer
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - 9000:9000
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /portainer:/data
    container_name: portainer
    labels:
      - "traefik.backend=portainer"
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:portainer.kalisio.xyz"

networks:
  traefik:
    external: true
