debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
  	[[entryPoints.https.tls.certificates]]
    certFile = "./server.cert"
    keyFile = "./server.key"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "kalisio.com"
watch = true
exposedbydefault = false

[acme]
email = "luc.claustres@kalisio.com"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
[acme.httpChallenge]
entryPoint = "http"
