debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
  	[[entryPoints.https.tls.certificates]]
  	# For dev tests with self-signed certificates
    #certFile = "./server.cert"
    #keyFile = "./server.key"
  [entryPoints.admin]
  address = ":8080"
  # If we add auth we need to encrypt this file
  #[entryPoints.admin.auth]
  #   [entryPoints.admin.auth.basic]
  #     users = [
  #       "admin-traefik:xxx"
  #     ]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "kalisio.xyz"
watch = true
exposedbydefault = false

[ping]
entryPoint = "http"

[metrics]
  [metrics.prometheus]
  entryPoint = "http"
  buckets = [0.1,0.3,1.2,5.0]

[api]
entryPoint = "admin"
dashboard = true

[accessLog]
filePath = "/logs/access.log"

[acme]
email = "luc.claustres@kalisio.xyz"
storage = "acme/acme.json"
entryPoint = "https"
# For dev tests
# caServer = "https://acme-staging.api.letsencrypt.org/directory"
OnHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"
  [[acme.domains]]
  main = "kalisio.xyz"
