version: '3.5'

services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    healthcheck:
      test: ["CMD", "wget", "-q", "--tries=1", "--spider", "http://localhost:5000/v2"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 1m
    networks:
      - kaabah-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  kaabah-network:
    name: ${DOCKER_NETWORK}
    external: true
