version: '3.5'

services:
  traefik:
    image: traefik:1.7-alpine
    command: --api --docker.endpoint=${DOCKER_HOST} --acme.email=${CONTACT} --acme.caServer=${CA_SERVER}
    volumes:
      - ./../configs/traefik/traefik.toml:/traefik.toml    
      - $HOME/.docker:/tls
      - ./../logs:/logs
      - ./../acme:/acme
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
    ports:
      - target: 80
        protocol: tcp
        published: 80
        mode: host
      - target: 443
        protocol: tcp
        published: 443
        mode: host
    networks:
      - kaabah-network
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.role == manager
      labels:
        - "traefik.backend=traefik"
        - "traefik.enable=true"      
        - "traefik.docker.network=kaabah-network"
        - "traefik.port=8080"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.auth.basic=${AUTH_USER}:${AUTH_PASSWORD}"
        - "traefik.frontend.rule=Host:traefik.${SUBDOMAIN}"
        - "traefik.frontend.headers.customResponseHeaders=X-XSS-Protection: 1; mode=block"        
      restart_policy:
        condition: on-failure

networks:
  kaabah-network:
    name: ${DOCKER_NETWORK}
    external: true