debug = false

defaultEntryPoints = ["http"]


[traefikLog]
filePath = "/logs/traefik.log"

[accessLog]
filePath = "/logs/access.log"

[entryPoints]
  [entryPoints.http]
  address = ":80"

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false

[ping]
entryPoint = "http"

[metrics]
  [metrics.prometheus]
  entryPoint = "http"
  buckets = [0.1,0.3,1.2,5.0]

[api]
entryPoint = "admin"
dashboard = true


