version: '3.5'

services:
  traefik:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.20'
          memory: 200M

  grafana:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
        reservations:
          cpus: '0.20'
          memory: 200M