#!/bin/bash

usage() {
  echo "usage: k-node-exec --command|-c <node_id> <command>"
  echo "usage: k-node-exec --script|-s <node_id> <script> [arguments...]"
}

help() {
  echo "Executes a command or a script a on the given node"
  usage
}

setup_ssh_agent() {
  if [ "$K_USER" == "root" ]; then
    K_HOME=/root
  else
    K_HOME=/home/$K_USER
  fi
  eval "$(ssh-agent -s)" > /dev/null
  ssh-add $K_HOME/.ssh/ssh.pem > /dev/null 2>&1
}

exec_command()
{
  NODE_IP=$1
  COMMAND=$2
  
  setup_ssh_agent

  ssh -o StrictHostKeyChecking=no $K_USER@$NODE_IP "$COMMAND"
}

exec_script()
{
  NODE_IP=$1
  SCRIPT=$2
  ARGUMENTS=$3
  
  setup_ssh_agent

  # Provision the script
  scp -o StrictHostKeyChecking=no "$SCRIPT" $K_USER@$NODE_IP:/tmp

  # Run the script
  REMOTE_SCRIPT=/tmp/`basename $SCRIPT`
  exec_command $NODE_IP "$REMOTE_SCRIPT $ARGUMENTS"
}

if [ "$#" -ne 3 ] && [ "$#" -ne 4 ]; then
  echo error: illegal number of arguments
  usage
  exit 1
fi

K_USER=${SUDO_USER:-$USER}
NODE_IP="$(docker inspect -f {{.Status.Addr}} $2)"

case $1 in
  -h|--help) help;;
  -c|--command) exec_command $NODE_IP "$3";;
  -s|--script) exec_script $NODE_IP "$3" "$4";;
  *) echo error: unknonw argument "$1"; usage
esac
