#!/bin/bash

usage() {
  echo "usage: k-node-exec --command|-c <node_id> <command>"
  echo "usage: k-node-exec --script|-s <node_id> <script> [arguments...]"
}

help() {
  echo "Executes a command or a script a on the given node"
  usage
}

exec_command()
{
  NODE_IP=$1
  COMMAND=$2
  
  ssh -i $HOME/.ssh/ssh.pem -o StrictHostKeyChecking=no $K_USER@$NODE_IP "$COMMAND"
}

exec_script()
{
  NODE_IP=$1
  SCRIPT=$2
  ARGUMENTS=$3
  
  # Provision the script
  scp -i $HOME/.ssh/ssh.pem -q -o StrictHostKeyChecking=no "$SCRIPT" $K_USER@$NODE_IP:/tmp

  # Run the script
  REMOTE_SCRIPT=/tmp/`basename $SCRIPT`
  exec_command $NODE_IP "chmod u+x $REMOTE_SCRIPT && $REMOTE_SCRIPT $ARGUMENTS"
}

if [ "$#" -ne 3 ] && [ "$#" -ne 4 ]; then
  echo error: illegal number of arguments
  usage
  exit 1
fi

K_USER=${SUDO_USER:-$USER}
NODE_IP="$(docker inspect -f {{.Status.Addr}} $2)"

case $1 in
  -h|--help) help;;
  -c|--command) exec_command $NODE_IP "$3";;
  -s|--script) exec_script $NODE_IP "$3" "$4";;
  *) echo error: unknonw argument "$1"; usage
esac
