#!/bin/bash

usage() {
  echo "usage: k-stack-check <stack> [starting_duration]"
}

help() {
  echo "Checks the health of the services of the given stack"
  usage
}

exec() {
  local STARTING_DURATION=${2:-300}
  local SERVICES=`docker stack services --format="{{.Name}}" $1`
  for SERVICE in $SERVICES; do
    echo checking service $SERVICE
    k-service-check $SERVICE $STARTING_DURATION
  done
}

if [ -z "$1" ]; then
   usage
   exit 1
fi

if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]; then
  echo error: illegal number of arguments
  usage
  exit 1
fi

case $1 in
  -h|--help) help;;
  *) exec "$1" "$2"
esac

