#!/bin/bash

usage() {
  echo "usage: k-swarm-prune"
}

help() {
  echo Remove all unused containers, networks, dangling images and volumes
  usage
}

exec() {
  k-node-foreach -c "docker system prune -f"
}

if [ "$#" -ne 0 ]; then
  echo error: illegal number of arguments
  usage
  exit 1
fi

case $1 in
  -h|--help) help;;
  *) exec
esac