#!/bin/bash

usage() {
  echo "usage: k-swarm-check [starting_duration]"
}


help() {
  echo "Checks the health of the services"
  usage
}

exec() {
  local STARTING_DURATION=${1:-300}
  local SERVICES=`docker service ls --format="{{.Name}}"`
  for SERVICE in $SERVICES; do
    echo checking service $SERVICE
    k-service-check $SERVICE $STARTING_DURATION
  done
}

if [ "$#" -ne 0 ] && [ "$#" -ne 1 ]; then
  echo error: illegal number of arguments
  usage
  exit 1
fi

case $1 in
  -h|--help) help;;
  *) exec "$1"
esac
