#!/bin/bash

usage() {
  echo "usage: k-worker-list [--id-only|-i]"
}

help() {
  echo "Lists the worker nodes"
  usage
}

exec() {
  if [ "$1" == "id-only" ]; then
    docker node ls -f role=worker | grep Ready | grep Active | cut -d' ' -f1
  else
    docker node ls -f role=worker | grep Ready | grep Active
  fi
}

if [ "$#" -ne 0 ] && [ "$#" -ne 1 ]; then
  echo error: illegal number of arguments
  usage
  exit 1
fi

case $1 in
  -h|--help) help;;
  --id-only|-i) exec id-only;;
  '') exec;;
  *) echo error: unknonw argument "$1"; usage
esac
