version: '3.5'

services:
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    networks:
      - platform-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.backend=portainer"
        - "traefik.enable=true"      
        - "traefik.docker.network=${PLATFORM}_network"
        - "traefik.port=9000"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:portainer.${PLATFORM}.${DOMAIN}"
      restart_policy:
        condition: on-failure

networks:
  platform-network:
    external:
      name: ${PLATFORM}_network