version: '3.5'

services:
  portainer:
    image: portainer/portainer
    command: --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - swarm-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.backend=portainer"
        - "traefik.enable=true"      
        - "traefik.docker.network=swarm-network"
        - "traefik.port=9000"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.auth.basic=${AUTH_USER}:${AUTH_PASSWORD}"
        - "traefik.frontend.rule=Host:portainer.${SUBDOMAIN}.${DOMAIN}"
      restart_policy:
        condition: on-failure
    depends_on:
      - traefik

networks:
  swarm-network:
    name: ${SWARM_NETWORK}
    external: true