version: '3.5'

services:
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - swarm-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.backend=portainer"
        - "traefik.enable=true"      
        - "traefik.docker.network=swarm-network"
        - "traefik.port=9000"
        - "traefik.frontend.entryPoints=http"
        - "traefik.frontend.rule=Host:portainer.${WORKSPACE}.${DOMAIN}"
      restart_policy:
        condition: on-failure
    depends_on:
      - traefik

networks:
  swarm-network:
    external: true