version: '3.5'

services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    networks:
      - kaabah-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  kaabah-network:
    name: ${DOCKER_NETWORK}
    external: true
