version: '3.5'

services:
  traefik:
    image: traefik:1.5.4
    command: --docker.domain=${DOMAIN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/traefik/traefik.toml:/traefik.toml
    ports:
      - target: 80
        protocol: tcp
        published: 80
        mode: host
      - target: 443
        protocol: tcp
        published: 443
        mode: host
      - target: 8080
        protocol: tcp
        published: 8080
        mode: host
    networks:
      - swarm-network
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.role == manager
      labels:
        - "traefik.backend=traefik"
        - "traefik.enable=true"      
        - "traefik.docker.network=swarm-network"
        - "traefik.port=8080"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:traefik.${WORKSPACE}.${DOMAIN}"
      restart_policy:
        condition: on-failure

networks:
  swarm-network:
    external: true