version: '3.5'

services:
  traefik:
    image: traefik
    command: --api --docker --docker.domain=${DOMAIN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/traefik/traefik.toml:/traefik.toml
      - ./acme:/acme
      - ./logs:/logs
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - platform-network
    deploy:
      labels:
        - "traefik.backend=traefik"
        - "traefik.enable=true"      
        - "traefik.docker.network=${PLATFORM}_network"
        - "traefik.port=8080"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:traefik.${PLATFORM}.${DOMAIN}"
    restart: unless-stopped

networks:
  platform-network:
    name: ${PLATFORM}_network