#!/bin/bash
NODE_ID=$1

usage()
{
cat << EOF
Lists the labels attached to a given node
usage: k-label-list <node_id>
EOF
}

if [ -z "$NODE_ID" ]; then
   usage
   exit 1
fi

docker node inspect -f '{{ range $k, $v := .Spec.Labels }}{{ $k }}={{ $v }} {{end}}' $NODE_ID
