#!/bin/bash

usage() {
  echo "usage: k-label-add <node_id> <labels>"
}

help() {
  echo "Adds the specified labels to a given node"
  usage
}

exec() {
  local NODE_ID=$1
  local LABELS=$2
  for LABEL in $LABELS; do
    if [ "$LABEL" != "" ]; then
      docker node update --label-add $LABEL $NODE_ID > /dev/null
    fi
  done
}

if [ "$#" -ne 2 ]; then
  echo error: illegal number of arguments
  usage
  exit 1
fi

case $1 in
  -h|--help) help;;
  *) exec $1 $2
esac


