#!/bin/bash

usage() {
  echo "usage: k-label-list <node_id>"
}

help() {
  echo "Lists the labels attached to a given node"
}

exec() {
  local NODE_ID=$1
  docker node inspect -f '{{ range $k, $v := .Spec.Labels }}{{ $k }}={{ $v }} {{end}}' $NODE_ID
}

if [ "$#" -ne 1 ]; then
  echo error: illegal number of arguments
  usage
  exit 1
fi

case $1 in
  -h|--help) help;;
  *) exec "$1"
esac
