#!/bin/bash
NODE_ID=$1
COMMAND=$2

usage()
{
cat << EOF
Executes a command on the given node
usage: k-node-exec <node_id> <command>
EOF
}

K_USER=${SUDO_USER:-$USER}
if [ "$K_USER" == "root" ]; then
  K_HOME=/root
else
  K_HOME=/home/$K_USER
fi

if [ -z "$NODE_ID" ]; then
   usage
   exit 1
fi

if [ -z "$COMMAND" ]; then
   usage
   exit 1
fi

NODE_IP="$(sudo docker inspect -f {{.Status.Addr}} ${NODE_ID})"

eval "$(ssh-agent -s)" > /dev/null
ssh-add $K_HOME/.ssh/ssh.pem > /dev/null 2>&1

ssh -o StrictHostKeyChecking=no $K_USER@$NODE_IP "$COMMAND"
