#!/bin/bash

usage() {
  echo "usage: k-service-check <service_id>"
}


help() {
  echo "Checks the status of the given service"
  usage
}

exec() {
  docker service ps --no-trunc $SERVICE_ID
}

if [ -z "$1" ]; then
   usage
   exit 1
fi

if [ "$#" -ne 1 ]; then
  echo error: illegal number of arguments
  usage
  exit 1
fi

case $1 in
  -h|--help) help;;
  *) exec
esac
