#!/bin/bash

usage() {
  echo "usage: k-swarm-info"
}

help() {
  echo "Displays the main information on the cluster"
  usage
}

exec() {
  # list the nodes
  echo "Nodes ----------"
  docker node ls
  # list the labels
  echo "Labels ---------"
  echo -e "ID\t\t\t\tLABELS"
  local WORKER_IDS=`docker node ls -q -f role=worker`
  for WORKER_ID in $WORKER_IDS; do
    echo -e "$WORKER_ID\t`k-label-list $WORKER_ID`"
  done
  # list the services
  echo "Services ------"
  docker service ls
}

if [ "$#" -ne 0 ]; then
  echo error: illegal number of arguments
  usage
  exit 1
fi

case $1 in
  -h|--help) help;;
  *) exec
esac
