#!/bin/bash

usage() {
  echo "usage: k-swarm-prune"
}

help() {
  echo "Clears the swarm"
  usage
}

exec() {
  K_SUDO=""
  if [ "$SUDO_USER" != "" ]; then
    K_SUDO="sudo"
  fi

  # Delete the stopped container
  $K_SUDO docker container prune -f
  k-worker-foreach -c "$K_SUDO docker container prune -f"

  # Delete the unused images
  $K_SUDO docker image prune -f
  k-worker-foreach -c "$K_SUDO docker image prune -f"

  # Delete the unused volumes
  $K_SUDO docker volume prune -f
  k-worker-foreach -c "$K_SUDO docker image prune -f"

  # Delete the unused networks 
  $K_SUDO docker network prune -f
  k-worker-foreach -c "$K_SUDO docker network prune -f"
}

if [ "$#" -ne 0 ]; then
  echo error: illegal number of arguments
  usage
  exit 1
fi

case $1 in
  -h|--help) help;;
  *) exec
esac