groups:
- name: disk-usage
  rules:

  - alert: root_disk_files_free
    expr: node_filesystem_files_free{mountpoint="/rootfs"} / node_filesystem_files{mountpoint="/rootfs"} < 0.25
    for: 30s
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} root disk is getting low on inodes"
      description: "{{ $labels.instance }} root disk is getting low on inodes (current value is: {{ $value }})"

  - alert: disk_fill_in_4_hours
    expr: predict_linear(node_filesystem_free{job="node-exporter"}[1h], 4 * 3600) < 0
    for: 2m
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} is getting low on free disk space"
      description: "{{ $labels.instance }} is getting low on free disk space."

