groups:
- name: disk-usage
  rules:

  - alert: root_free_files
    expr: node_filesystem_files_free{mountpoint="/rootfs"} / node_filesystem_files{mountpoint="/rootfs"} < 0.25
    for: 30s
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} root disk is getting low on inodes"
      description: "{{ $labels.instance }} root disk is getting low on inodes (current value is: {{ $value }})"

  - alert: root_free_disk_space
    expr: node_filesystem_avail_bytes{mountpoint="/rootfs"} / node_filesystem_size_byte{mountpoint="/rootfs"} < 0.25
    for: 30s
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} is getting low on free disk space"
      description: "{{ $labels.instance }} is getting low on free disk space."

