
route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        api_url: 'https://hooks.slack.com/services/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'
        channel: '#alerts'